name: VYF
favicon: null
layout_spectrum: 0.3962455962318927
typography_spectrum: 0.37786739435978234
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.8056999843101948
  lightness: 0.7772353077307343
  saturation: 0.5285374170634896
  rhythmicContrast: 0.6806873108725995
purpose: []
