name: VYF
favicon: null
layout_spectrum: 0.3962455962318927
typography_spectrum: 0.37786739435978234
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.875
  lightness: 0.9375
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
